# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='logo_url',
            field=models.CharField(max_length=250),
        ),
    ]
