# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('logo_url', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('faculty', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('photo_url', models.CharField(blank=True, max_length=250, null=True)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('url_1', models.URLField(blank=True, null=True)),
                ('url_2', models.URLField(blank=True, null=True)),
                ('url_3', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('logo_url', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=50)),
                ('responsibilities', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.TextField()),
                ('technologies', models.TextField()),
                ('URL', models.CharField(max_length=50)),
                ('logo_url', models.CharField(max_length=250)),
                ('device', models.TextField()),
                ('description', models.TextField()),
                ('finish', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologies', models.TextField()),
                ('frameworks', models.TextField()),
                ('data_bases', models.TextField()),
                ('tools', models.TextField()),
                ('operating_systems', models.TextField()),
            ],
        ),
    ]
