# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_academics_basicinfo_experience_projects_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcometext',
            name='add_date',
        ),
    ]
