# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20170525_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='github',
            new_name='github_login',
        ),
        migrations.RenameField(
            model_name='basicinfo',
            old_name='keybase',
            new_name='keybase_login',
        ),
    ]
