# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20170526_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='github_login',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='keybase_login',
            field=models.TextField(blank=True, null=True),
        ),
    ]
