# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keybase_api', '0002_auto_20170607_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keybasekey',
            old_name='keybase_login',
            new_name='login',
        ),
    ]
