# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('url_1', models.URLField()),
                ('url_2', models.URLField()),
                ('url_3', models.URLField()),
                ('text', models.TextField(max_length=250)),
            ],
        ),
    ]
