# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0002_auto_20170519_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='photo_url',
            field=models.CharField(max_length=100),
        ),
    ]
