# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0003_auto_20170520_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='photo_url',
            field=models.CharField(max_length=250),
        ),
    ]
