# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0004_auto_20170520_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='add_date',
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='photo_url',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='url_1',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='url_2',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='url_3',
            field=models.URLField(default=None),
        ),
    ]
