# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0005_auto_20170524_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='photo_url',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='text',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='url_1',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='url_2',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='url_3',
            field=models.URLField(null=True),
        ),
    ]
