# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academics',
            old_name='responsibilities',
            new_name='description',
        ),
    ]
