# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20170519_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='school_name',
            field=models.CharField(max_length=50),
        ),
    ]
