# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_github_name', models.TextField(default='morg')),
                ('repo_github_description', models.TextField(default='Put your wardrobe to python!')),
                ('repo_github_html_url', models.TextField(default='https://github.com/mkopr/morg')),
                ('repo_github_clone_url', models.TextField(default='https://github.com/mkopr/morg.git')),
                ('repo_github_created', models.TextField(default='2017-02-09')),
                ('repo_github_updated', models.TextField(default='2017-04-22')),
                ('repo_github_laguage', models.TextField(default='Python')),
            ],
        ),
        migrations.CreateModel(
            name='GithubUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_login', models.TextField(default='mkopr')),
                ('github_avatar_link', models.TextField(default='https://avatars0.githubusercontent.com/u/23700733?v=3')),
                ('github_user_name', models.TextField(default='Marcin Koprek')),
                ('github_number_of_repos', models.TextField(default=2)),
                ('github_create_account', models.TextField(default='2016-11-23')),
                ('github_account_url', models.TextField(default='https://github.com/mkopr')),
            ],
        ),
    ]
