# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuserdata',
            name='hello',
            field=models.TextField(default='world'),
        ),
    ]
