# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('github_api', '0003_remove_githubuserdata_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('html_url', models.URLField()),
                ('clone_url', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=39)),
                ('avatar_url', models.URLField()),
                ('user_name', models.CharField(max_length=255)),
                ('repo_count', models.PositiveSmallIntegerField()),
                ('account_created_at', models.DateTimeField()),
                ('account_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='GithubRepoData',
        ),
        migrations.DeleteModel(
            name='GithubUserData',
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='github_api.GithubUser'),
        ),
    ]
