# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('language', models.TextField()),
                ('technologies', models.TextField()),
                ('URL', models.CharField(max_length=50)),
                ('logo_url', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('add_date', models.DateField()),
            ],
        ),
    ]
