# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='device',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
