# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170520_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='logo_url',
            field=models.CharField(max_length=250),
        ),
    ]
