# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20170520_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='add_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='projects',
            name='finish',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
