# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170524_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
